publiclibrary/books/models.py
from publiclibrary import db

class Books(db.Model):
    
    __tablename__="books"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    author = db.Column(db.String(20))
    year_published  = db.Column(db.Integer)
    type = db.Column(db.Integer)
    books_loans = db.relationship("Loans", backref="Books", lazy=True)

    def __init__(self,name,author,year_published,type):
        self.name=name
        self.author=author
        self.year_published=year_published
        self.type=type

publiclibrary/books/views.py
from flask import Blueprint, Flask, render_template, request
from publiclibrary import db
from publiclibrary.books.models import Books
from publiclibrary.core.util import del_func

books= Blueprint('books',__name__,template_folder="templates")

##############################################################################
########################## start of book functions ###########################
##############################################################################
@books.route("/addbook/", methods=['POST','GET'])
def add_book():
    #add book function
    if request.method=='POST':
            new_book=request.json
            newBook=Books(new_book['nm'], new_book['auth'], new_book['year'], new_book['type'])
            db.session.add(newBook)
            db.session.commit()
            return 'success'
    return 'nothing'

@books.route("/findbook/", methods=['POST','GET'])
@books.route("/findbook/<ind>", methods=['DELETE','GET'])
def find_book(ind=-1):
    #find book by name - also can remove books once found
    msg=del_func(int(ind), Books,"Book") if int(ind)>0 else ["None","None"]
    list=[{"id":book.id,"name":book.name,"author":book.author,"year":book.year_published,"type":book.type} for book in db.session.query(Books).filter_by(name=request.json['nm']) if request.method=="POST"]
    return list
   
   
   
   
   
#    books=db.session.query(Books).filter_by(name=request.form.get('nm')).all() if request.method=="POST" else []
#     flag=True if len(books)>0 else False
#     render_info=del_func(ind,Books,"Book") if int(ind)>0 else ["None","None"]
#     return render_template('findbook.html', allbooks=Books.query.all(), books=books,flag=flag,msg=render_info[1],color=render_info[0])    

@books.route("/displayallbooks/", methods=['GET'])
@books.route("/displayallbooks/<ind>", methods=['DELETE','GET'])
def display_all_books(ind=-1):
    #displays all books in data base - books can also be removed with this function
    x=del_func(int(ind), Books,"book") if int(ind)>0 else ["None","None"]
    list=[]
    for book in Books.query.all():
        list.append({"id":book.id,"name":book.name,"author":book.author,"year":book.year_published,"type":book.type})
    return list




#    render_info=del_func(ind, Books,"Book") if int(ind)>0 else ["None","None"]
#     return render_template('displayallbooks.html',books=Books.query.all(),msg=render_info[1],color=render_info[0])
############################################################################
########################## end of book functions#########################
############################################################################

publiclibrary/books/templates/addbook.html
{% extends "layout.html" %}
{% block title %}Add Book{% endblock %}
{% block content %}
{% if msg %}
<div class="alert alert-success">
    <strong>Success!</strong> {{msg}}
  </div>
{% endif %}
<form action="{{ url_for('books.add_book') }}" name="add" method="POST">
    <h1>ADD BOOK TO DATABASE</h1>
    <p>Name:</p>
    <input type="text" name="nm" />
    <p>Author:</p>
    <input type="text" name="auth" />
    <p>Year Published:</p>
    <input type="text" name="year" />
    <p>Type:</p>
    <input type="text" name="type" />
    <br><input type="submit"  name="addbook" value="Add Book">
</form>
{% endblock %}

publiclibrary/books/templates/displayallbooks.html
{% extends "layout.html" %}
{% block title %}Display All Books{% endblock %}
{% block content %}
<h1>ALL BOOKS</h1>
{% if "green" in color %}
<div class="alert alert-success">
  <strong>Success!</strong> {{msg}}
</div>
{% elif "red" in color %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{msg}}
</div>
{% endif %}
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Author</th>
      <th>Publish Year</th>
      <th>Remove Book</th>
    </tr>
  </thead>
  {% for book in books %}
  <tr class="table-primary">
    <td>{{book.id}}</td>
    <td>{{book.name}}</td>
    <td>{{book.author}}</td>
    <td>{{book.year_published}}</td>
    <td>{% if book.books_loans %}active loans{% else %}no active loans {% endif %}</td>
    <td><a class="btn btn-danger" href="/displayallbooks/{{book.id}}" role="button">Remove</a></td>
  </tr>
  {% endfor %}
</table>




{% endblock %}

publiclibrary/books/templates/findbook.html
{% extends "layout.html" %}
{% block title %}Find Book{% endblock %}
{% block content %}
<form action="{{ url_for('books.find_book') }}" method="POST">
  <h1>FIND BOOK BY NAME</h1>
  <p>Name:</p>
  <input list="books" name="nm" required />
  <datalist id="books">
    {% for book in allbooks %}
    <option value="{{book.name}}">
      {% endfor %}
  </datalist>
  <br><input type="submit" value="Find!">
</form>
</br>

{% if "green" in color %}
<div class="alert alert-success">
  <strong>Success!</strong> {{msg}}
</div>
{% elif "red" in color %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{msg}}
</div>
{% endif %}
{% if flag %}
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Author</th>
      <th>Publish Year</th>
      <th>Remove Book</th>
    </tr>
  </thead>
  {% for book in books %}
  <tr class="table-primary">
    <td>{{book.id}}</td>
    <td>{{book.name}}</td>
    <td>{{book.author}}</td>
    <td>{{book.year_published}}</td>
    <td>{% if book.books_loans %}active loans{% else %}no active loans {% endif %}</td>
    <td> <a class="btn btn-danger" href="/findbook/{{book.id}}" role="button">Remove</a> </td>
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endblock%}