publiclibrary/loans/models.py
from publiclibrary import db





class Loans(db.Model):
    __tablename__ = "loans"

    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(db.Integer, db.ForeignKey("customers.id"), nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey("books.id"), nullable=False)
    loan_date = db.Column(db.Integer)
    return_date = db.Column(db.Integer)

    def __init__(self,customer_id,book_id,loan_date,return_date):
        self.customer_id=customer_id
        self.book_id=book_id
        self.return_date=return_date
        self.loan_date=loan_date

publiclibrary/loans/views.py
import datetime
from flask import Flask, render_template, request, Blueprint
from publiclibrary.loans.models import Loans
from publiclibrary.books.models import Books
from publiclibrary.customers.models import Customers
from publiclibrary.core.util import del_func
from publiclibrary import db

loans= Blueprint('loans',__name__,template_folder="templates")

##########################################################################
############################ start of loan functions #####################
##########################################################################א
@loans.route("/newloan/", methods=['POST','GET'])
def new_loan():
    #add a new loan to database
    # msg="None"
    if request.method=='GET':
        bboks=[{"id":book.id,"name":book.name,"author":book.author,"year":book.year_published,"type":book.type} for book in db.session.query(Books)]
        custs=[]
        for cust in Customers.query.all():
            custs.append({"id":cust.id,"name":cust.name,"age":cust.age,"city":cust.city})
        full_list={"books":bboks,"customers":custs}
        return full_list



    if request.method=='POST':
        current_book=db.session.query(Books).filter_by(id=int(request.json['book'])).first()
        if db.session.query(Loans).filter_by(book_id=current_book.id).first():
            msg="Book is Lent, Not Available"
        else:
            if current_book.type==1:
                return_date=datetime.date.today()+datetime.timedelta(days=10)
            elif current_book.type==2:
                return_date=datetime.date.today()+datetime.timedelta(days=5)
            else:
                return_date=datetime.date.today()+datetime.timedelta(days=2)
            newLoan=Loans(request.json["customer"], request.json["book"],datetime.date.today(),return_date )
            db.session.add(newLoan)
            db.session.commit()
            msg="Loan Approved"
        return 'success'
    # return render_template('newloan.html',books=Books.query.all(),customers=Customers.query.all(),msg=msg)

@loans.route("/lateloans/", methods=['GET'])
@loans.route("/lateloans/<ind>", methods=['DELETE','GET'])
def late_loans(ind=-1):
    #displays all the late loans - books can be return with this function
    list=[]
    for loan in Loans.query.all():
        if str(datetime.date.today()) > loan.return_date:
            list.append({"id":loan.id,"customer":loan.Customers.name,"book":loan.Books.name, "loandate":loan.loan_date,"returndate":loan.return_date})

    print(list)
    return list       

    # render_info=del_func(ind, Loans,"Loan") if int(ind)>0 else ["None","None"]
    # return render_template('lateloans.html', lateloans=Loans.query.all(), today=str(datetime.date.today()),msg=render_info[1],color=render_info[0])

@loans.route("/displayallloans/", methods=['GET'])
@loans.route("/displayallloans/<ind>", methods=['DELETE'])
def display_all_loans(ind=-1):
    #displays all loans - books can be returned with this function
    if request.method=="GET":
        list=[]
        for loan in Loans.query.all():
            # print(loan.Customers.name)
            list.append({"id":loan.id,"customer":loan.Customers.name,"book":loan.Books.name, "loandate":loan.loan_date,"returndate":loan.return_date})
        return list
    render_info=del_func(ind, Loans,"Loan") if int(ind)>0 else ["None","None"]

    print(render_info)
    return 'succes'
    # render_info=del_func(ind, Loans,"Loan") if int(ind)>0 else ["None","None"]
    # return render_template    ('displayallloans.html',loans=Loans.query.all(), today=str(datetime.date.today()),msg=render_info[1],color=render_info[0])

############################################################################
####################### end of loan functions ###############################
############################################################################

publiclibrary/loans/templates/displayallloans.html
{% extends "layout.html" %}
{% block title %}Display All Loans{% endblock %}
{% block content %}
<h1>ALL LOANS</h1>
{% if "green" in color %}
<div class="alert alert-success">
  <strong>Success! Loan Returned!</strong> {{msg}}
</div>
{% elif "red" in color %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{msg}}
</div>
{% endif %}
<table class="table">
    <thead>
      <tr class="warning">
        <th>Loan ID</th>
        <th>Book Name</th>
        <th>Loaner Name</th>
        <th>Return Date</th>
        <th>Loan Date</th>
        <th>Return Loan</th>
      </tr>
    </thead>
{% for loan in loans %}
{% if today > loan.return_date %}
<tr class="danger">
{% else %}
<tr class="info">
{% endif %}
    <td>{{loan.id}} </td>
    <td>{{loan.Books.name}} </td>
    <td>{{loan.Customers.name}}</td>
    <td>{{loan.return_date}} </td>
    <td>{{loan.loan_date}}</td>
    <td><a class="btn btn-danger" href="/displayallloans/{{loan.id}}">Return Book</a> </td>
</tr>
{% endfor %}
</table>

{% endblock %}

publiclibrary/loans/templates/lateloans.html
{% extends "layout.html" %}
{% block title %}Late Loans{% endblock %}
{% block content %}
<h1>LATE LOANS</h1>
{% if "green" in color %}
<div class="alert alert-success">
  <strong>Success! Loan Returned!</strong> {{msg}}
</div>
{% elif "red" in color %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{msg}}
</div>
{% endif %}

<table class="table">
  <thead>
    <tr class="info">
      <th>Loan ID</th>
      <th>Book Name</th>
      <th>Loaner Name</th>
      <th>Return Date</th>
      <th>Loan Date</th>
      <th>Return Loan</th>
    </tr>
  </thead>
  {% for loan in lateloans %}
  {% if today > loan.return_date %}
  <tr class="danger">
    <td>{{loan.id}} </td>
    <td>{{loan.Books.name}} </td>
    <td>{{loan.Customers.name}}</td>
    <td>{{loan.return_date}} </td>
    <td>{{loan.loan_date}}</td>
    <td><a class="btn btn-danger" href="/lateloans/{{loan.id}}">Return Book</a> </td>
    {% endif %}
  </tr>
  {% endfor %}
</table>

{% endblock %}

publiclibrary/loans/templates/newloan.html
{% extends "layout.html" %}
{% block title %}New Loan{% endblock %}
{% block content %}
<h1>ADD NEW LOAN</h1>    
{% if "Approved" in msg %}
<div class="alert alert-success">
    <strong>Success!</strong> {{msg}}
  </div>
  {% elif "Lent" in msg %}
  <div class="alert alert-danger">
    <strong>Failed!</strong> {{msg}}
  </div>
  {% endif %}
<form action="{{ url_for('loans.new_loan') }}" name="add" method="POST">
    <label>Choose a Customer:</label>
    <select name="customer">
        {% for cust in customers%}
        <option name="cust_id" value="{{cust.id}}">ID: {{cust.id}} Name: {{cust.name}}</option>
        {% endfor %}
        
    </select>

    <br><br>
    <label>Choose a Book:</label>
    <select name="book">
      {% for book in books %}
        <option name="book_id" value="{{book.id}}">ID: {{book.id}} Name: {{book.name}}</option>
        {% endfor %}
    </select>
    <br><br>
    <input type="submit" value="Add Loan">
</form>

{% endblock %}