publiclibrary/customers/models.py
from publiclibrary import db

class Customers(db.Model):

    __tablename__ = 'customers'
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(15))
    city = db.Column(db.String(15))
    age = db.Column(db.Integer)
    customer_loans = db.relationship("Loans", backref="Customers", lazy=True)

    def __init__(self, name, city, age):
        self.name=name
        self.city=city
        self.age=age

# db.create_all()

publiclibrary/customers/views.py
import json
from flask import Blueprint, Flask, render_template, request
from publiclibrary import db
from publiclibrary.core.util import del_func
from publiclibrary.customers.models import Customers

customers= Blueprint('customers',__name__,template_folder="templates") 

##############################################################################
##################### start of customer functions ###########################
##############################################################################
@customers.route("/addcustomer/", methods=['POST','GET'])
def add_customer():
    #add customer to database
    if request.method=='POST':
        new_customer=request.json
        newCustomer=Customers(new_customer['nm'],new_customer['ct'],new_customer['age'])
        db.session.add(newCustomer)
        db.session.commit()
    return 'success'
        # return render_template('addcustomer.html', msg="Customer Added Succsefully!")
    # return render_template('addcustomer.html')

@customers.route("/findcustomer/", methods=['POST'])
@customers.route("/findcustomer/<ind>", methods=['DELETE'])
def find_customer(ind=-1):
    #find customer by name - also customers can be removed once found
    msg=del_func(int(ind), Customers,"Customer") if int(ind)>0 else ["None","None"]
    list=[{"id":cust.id,"name":cust.name,"age":cust.age,"city":cust.city} for cust in db.session.query(Customers).filter_by(name=request.json['nm']) if request.method=="POST"]
    return list

@customers.route("/displayall/", methods=['GET'])
@customers.route("/displayall/<ind>", methods=['DELETE'])
def display_all(ind=-1):
    #display all customers - customers can also be removed with this function
    x=del_func(int(ind), Customers,"Customer") if int(ind)>0 else ["None","None"]
    list=[]
    for cust in Customers.query.all():
        list.append({"id":cust.id,"name":cust.name,"age":cust.age,"city":cust.city})
    print(list)
    return list
##############################################################################
######################### end of customer functions ##########################
##############################################################################

publiclibrary/customers/templates/addcustomer.html
{% extends "layout.html" %}
{% block title %}Add User{% endblock %}
{% block content %}
{% if msg %}
<div class="alert alert-success">
    <strong>Success!</strong> {{msg}}
  </div>
{% endif %}
<h1>ADD CUSTOMER TO DATABASE</h1>
<br>
<form action="{{ url_for('customers.add_customer') }}" method="POST">
    <label>Name:</label>
    <input type="text" name="nm" required />
    <br>
    <label>City:</label>
    <input type="text" name="ct" required/>
    <br>
    <label>Age:</label>
    <input type="text" name="age" required/>
    <br><input type="submit" value="submit">
</form>
{% endblock %}

publiclibrary/customers/templates/displayallcustomers.html
{% extends "layout.html" %}
{% block title %}Find Customer{% endblock %}
{% block content %}
<h1>ALL CUSTOMERS</h1>
{% if "green" in color %}
<div class="alert alert-success">
  <strong>Success!</strong> {{msg}}
</div>
{% elif "red" in color %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{msg}}
</div>
{% endif %}
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>active loans</th>
    </tr>
  </thead>
  {% for name in names %}
  <tr class="table-primary">
    <td>{{name.id}}</td>
    <td>{{name.name}}</td>
    <td>{{name.age}}</td>
    <td>{% if name.customer_loans %}
      active loans
      {% else %}
      no active loans
      {% endif %}</td>
    <td>
      <a class="btn btn-danger" href="/displayall/{{name.id}}" role="button">Remove</a>

    </td>
  </tr>
  {% endfor %}
</table>




{% endblock %}

publiclibrary/customers/templates/findcustomer.html
{% extends "layout.html" %}
{% block title %}Find Customer{% endblock %}
{% block content %}
<form action="{{ url_for('customers.find_customer') }}" method="POST">
  <h1>FIND CUSTOMER BY NAME</h1>
  <p>Name:</p>
  <input list="customers" name="nm" required />
  <datalist id="customers">
    {% for customer in allcustomers %}
    <option value="{{customer.name}}">
    {% endfor %}
  </datalist>
  <br><input type="submit" value="Find!">
</form>
</br>

{% if "green" in color %}
<div class="alert alert-success">
  <strong>Success!</strong> {{msg}}
</div>
{% elif "red" in color %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{msg}}
</div>
{% endif %}
{% if flag %}
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>active loans</th>
    </tr>
  </thead>
  {% for name in names %}
  <tr class="table-primary">
    <td>{{name.id}}</td>
    <td>{{name.name}}</td>
    <td>{{name.age}}</td>
    <td>{% if name.customer_loans %}active loans{% else %}no active loans {% endif %}</td>
    <td> <a class="btn btn-danger" href="/findcustomer/{{name.id}}" role="button">Remove</a> </td>
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endblock%}